[package]
name = "toda"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
nix = "0.17.0"
anyhow = "1.0.31"
fuse = "0.3"
time = "0.1"
signal-hook = "0.1"